# Generated by Django 4.0.6 on 2022-07-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_model_layer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='medal',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze'), ('OLTIN', 'Oltin'), ('KUMUSH', 'Kumush'), ('BRONZA', 'Bronza')], max_length=10),
        ),
    ]
